<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
        <div class="content">
            <h1 class="text-center">Inicio de sesión</h1>
            <div class="text-center"><a class="btn btn-default" href="<?= $link ?>">Iniciar sesión en Google</a></div>
        </div>
        
    </body>
</html>
