<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Perfil</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <style type="text/css">
            .content{
                max-width: 700px;
                position: relative;
                display: block;
                left: 50%;
                margin-left: -350px;
                text-align:center;
            }
        </style>
    </head>
    <body>
        <div class="content">
            <h1 class="text-center">Datos del usuario</h1>
            <p class="mt-4"><b>Nombre:</b> <?= $user["Name"] ?></p>
            <p class="mt-2"><b>Apellidos:</b> <?= $user["Surname"] ?></p>
            <p class="mt-2"><b>Correo electrónico:</b> <?= $user["Email"] ?></p>
            <a href="/logout" class="btn btn-danger">Cerrar sesión</a>
        </div>
        
    </body>
</html>
